version: '3'
services:
  singlenode:
    container_name: singlenode
    image: ravendb/ravendb:5.2-ubuntu-latest
    ports:
      - 8080:8080
      - 38888:38888
    extra_hosts:
      - "host.docker.internal:host-gateway"      
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - "RAVEN_ServerUrl=http://172.28.1.1:8080"
      - "RAVEN_PublicServerUrl=http://host.docker.internal:8080"
      - "RAVEN_ServerUrl_Tcp=tcp://172.28.1.1:38888"
      - "RAVEN_PublicServerUrl_Tcp=tcp://host.docker.internal:38888"
    networks:
        singlenode_network:
            ipv4_address: 172.28.1.1
  singlenodesetup:
    container_name: singlenodesetup
    image: mcr.microsoft.com/powershell:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"      
    volumes:
      - ./setup_singlenode.ps1:/var/ravendb/setup_singlenode.ps1
    entrypoint: ["pwsh", "-command", "&./var/ravendb/setup_singlenode.ps1", "'${LICENSE}'", "host.docker.internal"]
    restart: "no" 
    depends_on:
      - singlenode
    networks:
        - singlenode_network
  leader:
    container_name: leader
    image: ravendb/ravendb:5.2-ubuntu-latest
    ports:
      - 8081:8080
      - 38889:38888
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - "RAVEN_ServerUrl=http://172.29.1.1:8080"
      - "RAVEN_PublicServerUrl=http://host.docker.internal:8081"
      - "RAVEN_ServerUrl_Tcp=tcp://172.29.1.1:38888"
      - "RAVEN_PublicServerUrl_Tcp=tcp://host.docker.internal:38889"
    networks:
        cluster_network:
            ipv4_address: 172.29.1.1
  follower1:
    container_name: follower1
    image: ravendb/ravendb:5.2-ubuntu-latest
    depends_on:
      - leader
    ports:
      - 8082:8080
      - 38890:38888
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - "RAVEN_ServerUrl=http://172.29.1.2:8080"
      - "RAVEN_PublicServerUrl=http://host.docker.internal:8082"
      - "RAVEN_ServerUrl_Tcp=tcp://172.29.1.2:38888"
      - "RAVEN_PublicServerUrl_Tcp=tcp://host.docker.internal:38890"
    networks:
        cluster_network:
            ipv4_address: 172.29.1.2
  follower2:
    container_name: follower2
    image: ravendb/ravendb:5.2-ubuntu-latest
    depends_on:
      - leader
    ports:
      - 8083:8080
      - 38891:38888
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - "RAVEN_ServerUrl=http://172.29.1.3:8080"
      - "RAVEN_PublicServerUrl=http://host.docker.internal:8083"
      - "RAVEN_ServerUrl_Tcp=tcp://172.29.1.3:38888"
      - "RAVEN_PublicServerUrl_Tcp=tcp://host.docker.internal:38891"
    networks:
        cluster_network:
            ipv4_address: 172.29.1.3
  clustersetup:
    container_name: clustersetup
    image: mcr.microsoft.com/powershell:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    volumes:
      - ./setup_cluster.ps1:/var/ravendb/setup_cluster.ps1
    entrypoint: ["pwsh", "-command", "&./var/ravendb/setup_cluster.ps1", "'${LICENSE}'", "host.docker.internal"]
    restart: "no" 
    depends_on:
      - leader
      - follower1
      - follower2
    networks:
        - cluster_network
networks:
    singlenode_network:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
    cluster_network:
        ipam:
            driver: default
            config:
                - subnet: 172.29.0.0/16